### ISSUE TITLE
Animation between activities

### ISSUE THREAD

**Issue by stasusov** [kyze8439690/RevealLayout#3]
Can i use this library for animation between activities? And how?
Thanks in advance

**Comment by locomain** [comment]
+1

**Comment by kyze8439690** [comment]
I think it is not so different from play animation in a fragment commit.

**Comment by kyze8439690** [comment]
Make an activity to be transparent, when play the animation in onCreate method, override the onbackpressed method, play the exit animation and post delay the super.onBackPressed method.
