### ISSUE TITLE
RevealLayout reverse animation for FragmentActivity

### ISSUE THREAD

**Issue by niteshkhatri** [kyze8439690/RevealLayout#5]
Hi. First of all thanks for such a great piece of code. I really liked it. I have a minor request for FragmentActivity class. Can you please provide RevealLayout reverse animation as well when we go to previous fragment by pressing back?

**Comment by kyze8439690** [comment]
I have tried to achieve this funciton, but I found that fragment class doesn't provide a onBackPressed() function like Activity. But not matter what, the layout has provide a reverse animation, the only thing to do is find a way to trigger it, may be pass a call from Activity? I will try to achieve that.

**Comment by niteshkhatri** [comment]
Thanks for your quick reply. I am eagerly waiting for your updated code.

**Comment by kyze8439690** [comment]
There is a little strange in this demo, because back animation only start when the last one is finished.
